version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fast_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: fast_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: project_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1@db:5432/fast_data
    volumes:
      - .:/app

volumes:
  postgres_data: