"""Исправления

Revision ID: 541eb8069589
Revises: 99b61e18dcdc
Create Date: 2026-08-19 18:16:00.012191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '541eb8069589'
down_revision: Union[str, Sequence[str], None] = '99b61e18dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'is_active')
    op.drop_column('wallets', 'currency')
    op.drop_column('wallets', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
