"""fix_wallet_structure

Revision ID: 99b61e18dcdc
Revises: ca0db9a77ace
Create Date: 2026-08-19 17:21:20.023484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b61e18dcdc'
down_revision: Union[str, Sequence[str], None] = 'ca0db9a77ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('wallet_address', sa.String(), nullable=False))
    op.add_column('wallets', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('wallets', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('wallets', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_wallets_wallet_address'), 'wallets', ['wallet_address'], unique=True)
    op.drop_column('wallets', 'amount')
    op.drop_column('wallets', 'operation_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('operation_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('wallets', sa.Column('amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wallets_wallet_address'), table_name='wallets')
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'created_at')
    op.drop_column('wallets', 'is_active')
    op.drop_column('wallets', 'currency')
    op.drop_column('wallets', 'wallet_address')
    # ### end Alembic commands ###
